### ISSUE TITLE
我加了个图片，实验了一下有点问题啊

### ISSUE THREAD

**Issue by jiazufei** [ios122/ios122#1]
文本增加长度，
cell做了些修改代码如图
![image](https://cloud.githubusercontent.com/assets/3351691/10656261/a498a662-78af-11e5-97c6-20dc87570396.png)
效果是这样的

另外我希望做成微博那样最多九张图片排列应该怎么处理呢？把最多9张图片罗列放到cell里还是专门放到一个view里，然后把view放到cell上，那这个view的宽高会变化，怎么处理好呢？

**Comment by jiazufei** [comment]
![1111](https://cloud.githubusercontent.com/assets/3351691/10656494/d7e8f6d2-78b1-11e5-9839-9bd5d2f58e8c.gif)

**Comment by ios122** [comment]
1. 我觉得效果和你的代码是对应的.
2.旋转屏幕时,你应该需要在屏幕旋转的方法里,去让tableView reloadData
3.关于微博9张图动态cell的效果,qq群里讨论过:a.你可以添加一个占位的view,用来放置图片,然后动态往view上添加图片; 2.你也可以放置一个collectionView;  无论哪种方式,你都需要在设置model时,动态设置这个占位的view的高度约束,最好使用 remake

**Comment by jiazufei** [comment]
正好碰到一个需求，cell里要放个高度不固定的 uiwebview，调一天了，高度总调不好

**Comment by ios122** [comment]
翻译过来,距离左 , 上 的距离必须是 8, 图片自身宽高必须是60; 距离底部的间距应该大于或等于8.

这个 iMageView高度是固定的.  webview高度不固定,但是你需要先根据内容自己给一个合适的高度,因为webView的高度和内容间 没有必然的联系,就像一个网页,你全屏看,缩放看,都可以显示.

最后说一句 Masonry 是对 Apple 的 AutoLayout机制的一种封装和简化;UITableView-FDTemplateLayoutCell 能正确工作的前提是, 你给cell提供的约束,足以确定一个cell的高度.

比如说: 如果你指定一个 view 和 cell 的top,left,bottom,right 都为0,此时是不足以确定cell的高度的,返回的height可能是0;

**Comment by jiazufei** [comment]
也就是说，如果不提前确定cell里的子视图高度，那么子视图返回的height 是0，
由于uiwebview的高度是在加载数据后才能计算出高度，滞后于以上要求的提前，那么就没办法自动适配cell高度了，应该如何解决呢？
因为我发现UILabel 设置number属性＝0的时候，也应该是设置字符串后返回的一个高度，神奇的事就发生了，cell自动适应高度了

**Comment by jiazufei** [comment]
而且另外的一个问题是，如果我给cell设置一个委托，当UIWebView返回高度的时候，委托父视图UITableView刷新，这样会产生死循环，当UITableView刷新时，UIWebView再次计算高度并委托父视图UITableView刷新

**Comment by ios122** [comment]
DIY.如果解决了,欢迎分享! 示例,仅作入门参考.具体深入使用,我是根据自己公司产品需要,有序进行.我想,你也一样!

**Comment by jiazufei** [comment]
谢谢！
