### ISSUE TITLE
JSPatch实例部分有错误

### ISSUE THREAD

**Issue by mengxiangjian13** [ios122/ios122#2]
demo.js中两个类名没有修改。

**Comment by Ruoyiming** [comment]
具体是哪一行呢 谢谢 方便我们尽快修改 避免误人子弟

**Comment by Ruoyiming** [comment]
@mengxiangjian13

**Comment by ios122** [comment]
改好了,示例是由 @Ruoyiming  提供了,添加到iOS122示例时,更改了 .h .m,但是 忘记修改demo.js了;

**Comment by mengxiangjian13** [comment]
@Ruoyiming 不好意思，没及时看到你的回复。是我写issue的时候写的不清楚。好在已经修改了。
